tasks:
  - name: terraform
    before: |
      source ./bin/set_tf_alias
      source ./bin/install_terrafrom_cli
      source ./bin/generate_trfc_credentials
      cp $PROJECT_ROOT=/terraform.tfvars.example $PROJECT_ROOT=/terraform.tfvars

  - name: sinatra
    before : |
      cd $PROJECT_ROOT
      cd terratowns_mock_server
      bundle install
      bundle exec ruby server.rb 

  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

  - name: http-server
    before: |
       npm install --global http-server
    command:
      http-server  
      
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform