#! /usr/bin/bash

PLUGIN_DIR=".terraform.d/plugins/local.provider/local/terratowns/1.0.0/"
PLUGIN_NAME= "terraform-provider-terratowns_v1.0.0"
# https://servian.dev/terraform-local-provider-and-registry-mirror-configuration-b963117dffa 
cd $PROJECT_ROOT/terraform-provider-terratowns

cp $PROJECT_ROOT/terraformrc /home/gitpod/terraformrc
rm -rf ~/.terraform.d/plugins
rm -rf $PROJECT_ROOT/.terraform.lock.hcl
go.build.-o.terraform-provider-terratowns_v1.0.0
mkdir -p $PLUGIN_DIR/x86_64
mkdir -p $PLUGIN_DIR/1.0.0/linux_amd64
cp $PLUGIN_NAME $PLUGIN_DIR/x86_64 
cp $PLUGIN_NAME $PLUGIN_DIR/linux_amd64